### ISSUE TITLE
Acesso restrito a logados

### ISSUE THREAD

**Issue by alencaranderson** [lmtsufape/participa#237]
Ao tentar acessar este endereço, está sendo solicitado informar login e senha: http://participa.ufape.edu.br/evento/visualizar/41

**Comment by jofernando** [comment]
O link para quem não está logado é [http://participa.ufape.edu.br/evento/41](http://participa.ufape.edu.br/evento/41)

**Comment by jofernando** [comment]
O que poderia ser feito é, utilizar o mesmo link e tratar isso no backend e redirecionar para a view adequada.

**Comment by alencaranderson** [comment]
Pode ser porque a pessoa não perceberá essa sutileza.

**Comment by jofernando** [comment]
O link para visualizar o evento para quem está logado ou é visitante, é [http://participa.ufape.edu.br/evento/visualizar/41](http://participa.ufape.edu.br/evento/visualizar/41)
