### ISSUE TITLE
Sugestão: opção de visualizar apenas os trabalhos que ainda não possuem revisor atribuído

### ISSUE THREAD

**Issue by felipeaquac** [lmtsufape/participa#240]
![image](https://user-images.githubusercontent.com/58593825/169602875-e0ca76ab-e842-421e-a206-9469684c60cf.png)

**Comment by felipeaquac** [comment]
Facilitaria quando estivessemos atribuíndo manualmente os revisores

**Comment by alencaranderson** [comment]
Eu acho excelente isto!
