### ISSUE TITLE
Criar novas etiquetas relativas a trabalhos

### ISSUE THREAD

**Issue by alencaranderson** [lmtsufape/participa#241]
Criar etiquetas para os textos Regras, Modelo de apresentação e Template que aparecem na área na tela do evento.

**Comment by jofernando** [comment]
@alencaranderson já tem regras e template nas etiquetas do eventos, seria só adicionar a de modelo de apresentação ou criar específicas para trabalho?

**Comment by lmts-ufape** [comment]
Acho que merece uma específica para trabalhos em geral. São muitas variações de termos. Agora mesmo, felipe me perguntava o que era a "validação", rs.
