### ISSUE TITLE
Problema com a logo do evento no celular

### ISSUE THREAD

**Issue by alencaranderson** [lmtsufape/participa#242]
Pelo celular, a logo do evento está ficando achatada:

![image](https://user-images.githubusercontent.com/105824278/169655977-29b892af-e388-4a98-a293-0cb391de1f73.png)

**Comment by KelwinJonas** [comment]
@alencaranderson vê se fica melhor assim
![comparativo](https://user-images.githubusercontent.com/45975077/170303734-08bcc6e5-fcff-40fd-a156-fe51517837e5.png)

**Comment by lmts-ufape** [comment]
Oxi. Tá ótimo!
