### ISSUE TITLE
Sugestão: Permitir acesso aos trabalhos pela tela "visualizar revisor"

### ISSUE THREAD

**Issue by felipeaquac** [lmtsufape/participa#243]
![image](https://user-images.githubusercontent.com/58593825/169813077-dfc943e0-db85-4666-99cd-0488cf9b21c5.png)

**Comment by felipeaquac** [comment]
Frequentemente temos que buscar algum trabalho que foi atribuido à um revisor específico. nesse caso é preciso anotar o titulo e procurar na tela "listar trabalhos" para conseguir acesso. Se houvesse link direto seria mais prático

**Comment by jofernando** [comment]
Closed by #255
