### ISSUE TITLE
Sugestão: incluir informação sobre andamento da revisão na tela de trabalhos.

### ISSUE THREAD

**Issue by felipeaquac** [lmtsufape/participa#254]
![image](https://user-images.githubusercontent.com/58593825/171621650-8762dc97-54bc-4968-b31a-e3f47a30277e.png)
Incluir nessa tela o status do trabalho. Se foi avaliado ou não. Alguns revisores não fizeram a avaliação e é necessário atribuir novos revisores. fazer isso se torna muito trabalhoso pois temos que ir à tela de revisores para descobrir quais são os trabalhos que necessitam ser redirecionados.

**Comment by lmts-ufape** [comment]
Acho boa a ideia, mas temos que ver visualmente como ficaria porque está bem lotado. Felipe edita a imagem para não aparecer os nomes, títulos etc, rs.
