### ISSUE TITLE
Não conseguimos obter mais do que uma avaliação por trabalho. 

### ISSUE THREAD

**Issue by felipeaquac** [lmtsufape/participa#265]
Apesar de conseguir atribuir múltiplos avaliadores para um mesmo trabalho, apenas uma avaliação é permitida. Acredito que não faz muito sentido enviar para mais de uma pessoa o trabalho se apenas uma conseguirá avaliar, fora o inconveniente do revisor de receber um resumo e não poder fazer nada com ele. 
A ideia de obter múltiplas avaliações é poder fazer uma média dos conceitos atribuídos e assim ter maior segurança e isonomia no processo avaliativo.

**Comment by lmts-ufape** [comment]
Pessoal, felipe me explicou como seria. Essa é urgente.

**Comment by felipeaquac** [comment]
Explicando melhor, a questão é que enviei o mesmo trabalho para vários revisores, mas apenas a avaliação do primeiro a avaliar é registrada. Os outros revisores recebem a notificação mas não conseguem avaliar
