### ISSUE TITLE
Erro ao tentar editar o formulário

### ISSUE THREAD

**Issue by felipeaquac** [lmtsufape/participa#281]
![image](https://user-images.githubusercontent.com/58593825/173929078-8c7e7b43-d90b-4b70-88c8-3438a6583231.png)

**Comment by felipeaquac** [comment]
Este erro apareceu ao tentar editar o formulário de avaliação. A mudança seria tornar visível ao autor algumas das perguntas do formulário.

**Comment by lmts-ufape** [comment]
Bom dia! Esse erro já foi registro em issue. Fechando...
