### ISSUE TITLE
Permitir que o criador do evento crie campos customizados de informação na inscrição geral ou nas atividades

### ISSUE THREAD

**Issue by lmts-ufape** [lmtsufape/participa#307]
As pessoas gostariam de pedir outras informações aos participantes para seus fins, tais como: formação, idade, sexo, etc, e essas informações não são coletadas no cadastro. Na prática seria: ao clicar no nome inscrever-se, abre um modal com os campos de informação que a organização quer coletar e daí a pessoa aperta o enviar. A mesma coisa nas oficinas, palestras etc. Se a coordenação não setou campos customizáveis, então fica como está.

**Comment by jofernando** [comment]
Tem essa tela que foi perdida com a atualização para facilitar a inscrição no evento. Podemos utilizar ela para atribuir campos ao formulário de inscrição no evento. Acho melhor só utilizar o formulário na inscrição do evento e as outras atividades utilizarem os dados do mesmo formulário.
![image](https://user-images.githubusercontent.com/24763793/183531450-53d0dc72-9ba9-4c0b-9f86-9174d13fabd4.png)
