### ISSUE TITLE
Desabilitar o botão / função de enviar trabalhos se não há submissão aberta no período

### ISSUE THREAD

**Issue by lmts-ufape** [lmtsufape/participa#309]

**Comment by jofernando** [comment]
O botão de submeter trabalho só está disponível fora do período de submissão se o usuário for coordenador do evento. O collapse continua ativo até a data de resultado como mostra imagem. 
![image](https://user-images.githubusercontent.com/24763793/183529672-c202125a-9a05-4d34-99d7-888a0536792d.png)
